[[headers]]
  for = "/*"
    [headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/error-500.html"
  to = "/500.htm"
  status = 500
  force = true
